events {}

http {
    server {
        listen 8500 ssl;
        server_name aiserver.digitrends.sa;

        ssl_certificate /etc/letsencrypt/live/aiserver.digitrends.sa/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/aiserver.digitrends.sa/privkey.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        location /mcp {
            proxy_pass http://mcp-app:8000/mcp;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_buffering off;
            proxy_read_timeout 300s;
        }
    }
}
